// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQjM2tXX6MzkOtInXyttNEy8C6D_8frM',
    appId: '1:684557538906:web:c937fa47a5db73e8e76a63',
    messagingSenderId: '684557538906',
    projectId: 'murkos-appsas',
    authDomain: 'murkos-appsas.firebaseapp.com',
    storageBucket: 'murkos-appsas.firebasestorage.app',
    measurementId: 'G-ZSKGWH8KY6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLYXRsOh-j95DKGf290c2CrJrbdH5mXCM',
    appId: '1:684557538906:ios:68a607e692e478d3e76a63',
    messagingSenderId: '684557538906',
    projectId: 'murkos-appsas',
    storageBucket: 'murkos-appsas.firebasestorage.app',
    iosBundleId: 'com.example.murkosappsas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLYXRsOh-j95DKGf290c2CrJrbdH5mXCM',
    appId: '1:684557538906:ios:68a607e692e478d3e76a63',
    messagingSenderId: '684557538906',
    projectId: 'murkos-appsas',
    storageBucket: 'murkos-appsas.firebasestorage.app',
    iosBundleId: 'com.example.murkosappsas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAQjM2tXX6MzkOtInXyttNEy8C6D_8frM',
    appId: '1:684557538906:web:3821e5bc2eee8b13e76a63',
    messagingSenderId: '684557538906',
    projectId: 'murkos-appsas',
    authDomain: 'murkos-appsas.firebaseapp.com',
    storageBucket: 'murkos-appsas.firebasestorage.app',
    measurementId: 'G-G5F9HG718L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_UsNrWtWszJlc_xE20nzIPInVwhb9gG0',
    appId: '1:457484690219:android:598b73e67ff1ea7284db6e',
    messagingSenderId: '457484690219',
    projectId: 'appsasmurkos',
    storageBucket: 'appsasmurkos.firebasestorage.app',
  );

}